# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            denovolyzeR
tagline:          'Statistical analyses of de novo genetic variants'
description:      'An integrated toolset for the analysis of de novo (sporadic) genetic sequence variants.'
url:              http://denovolyzer.org
baseurl:          /

author:
  name:           'James Ware'
  url:            https://twitter.com/dr_jamesware

paginate:         5
paginate_path:    "/news/page:num"

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/jamesware/denovolyzer
